export const $functions = Symbol('Fireschema - functions')
export const $schema = Symbol('Fireschema - schema')
export const $adapter = Symbol('Fireschema - adapter')
export const $collectionGroup = Symbol('Fireschema - collectionGroup')
export const $docLabel = Symbol('Fireschema - docLabel')
export const $allow = Symbol('Fireschema - allow')
