/* Auto generated by fireschema */
const importModule = (functionNames, modulePath) => {
  return !process.env['FUNCTION_NAME'] ||
    functionNames.includes(process.env['FUNCTION_NAME'])
    ? require(modulePath)
    : undefined
}
export const callable = {
  ...importModule(['callable-test'], './callable/test_'),
}
